name: discord notify

on:
  push:
    branches:
      - main  # change to master if your default branch is master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: send discord message
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                    "flags": 32768,
                    "components": [
                      {
                        "type": 17,
                        "accent_color": 9895830,
                        "spoiler": false,
                        "components": [
                          {
                            "type": 10,
                            "content": "<:github:1535885661683589161> changes in **${{github.actor}}**'s repositories:\n## [${{github.repository}} • ${{github.ref_name}}] new commit(s)\n"
                          },
                          {
                            "type": 14,
                            "divider": true,
                            "spacing": 1
                          },
                          {
                            "type": 10,
                            "content": "- [`${{github.sha}}`] ${{github.event.head_commit.message}} • **${{github.actor}}**"
                          },
                          {
                            "type": 14,
                            "divider": true,
                            "spacing": 1
                          },
                          {
                            "type": 10,
                            "content": "-# embed made by [@blasieuwu](https://blasieuwu.neocities.org)"
                          }
                        ]
                      }
                    ]
                  }' \
               "${{ secrets.DISCORD_WEBHOOK }}"
